Dependency update to the latest versions

diff --git a/vendor/github.com/gobuffalo/pop/v6/Makefile b/vendor/github.com/gobuffalo/pop/v6/Makefile
--- a/vendor/github.com/gobuffalo/pop/v6/Makefile
+++ b/vendor/github.com/gobuffalo/pop/v6/Makefile
@@ -1,15 +1,11 @@
+PACKAGE_NAME          := github.com/gobuffalo/pop
+GOLANG_CROSS_VERSION  ?= v1.18
+
 TAGS ?= "sqlite"
 GO_BIN ?= go
 
 install: deps
 	$(GO_BIN) install -tags ${TAGS} -v ./soda
-
-deps:
-	$(GO_BIN) get github.com/gobuffalo/release
-	$(GO_BIN) get -tags ${TAGS} -t ./...
-ifeq ($(GO111MODULE),on)
-	$(GO_BIN) mod tidy
-endif
 
 build:
 	$(GO_BIN) build -v .
@@ -17,25 +13,38 @@ build:
 test:
 	$(GO_BIN) test -tags ${TAGS} ./...
 
-ci-test:
-	$(GO_BIN) test -tags ${TAGS} -race ./...
-
 lint:
 	golangci-lint run
-
-update:
-	$(GO_BIN) get -u -tags ${TAGS}
-ifeq ($(GO111MODULE),on)
-	$(GO_BIN) mod tidy
-endif
-	make test
-	make install
-ifeq ($(GO111MODULE),on)
-	$(GO_BIN) mod tidy
-endif
 
 release-test:
 	./test.sh
 
+.PHONY: release-dry-run
+release-dry-run:
+	@docker run \
+		--rm \
+		--privileged \
+		-e CGO_ENABLED=1 \
+		--env-file .release-env \
+		-v /var/run/docker.sock:/var/run/docker.sock \
+		-v `pwd`:/go/src/$(PACKAGE_NAME) \
+		-w /go/src/$(PACKAGE_NAME) \
+		goreleaser/goreleaser-cross:${GOLANG_CROSS_VERSION} \
+		--rm-dist --skip-validate --skip-publish --snapshot
+
+.PHONY: release
 release:
-	release -y -f soda/cmd/version.go
+	@if [ ! -f ".release-env" ]; then \
+		echo "\033[91m.release-env is required for release\033[0m";\
+		exit 1;\
+	fi
+	docker run \
+		--rm \
+		--privileged \
+		-e CGO_ENABLED=1 \
+		--env-file .release-env \
+		-v /var/run/docker.sock:/var/run/docker.sock \
+		-v `pwd`:/go/src/$(PACKAGE_NAME) \
+		-w /go/src/$(PACKAGE_NAME) \
+		goreleaser/goreleaser-cross:${GOLANG_CROSS_VERSION} \
+		release --rm-dist
